# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Parq < Formula
  desc "A CLI for examining parquet files."
  homepage "https://github.com/a-poor/parq"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/a-poor/parq/releases/download/v0.1.0/parq_0.1.0_Darwin_arm64.tar.gz"
      sha256 "bdce7527192d218978a0fa0312bc168353098c5f803083b318686b0b9eaf62a8"

      def install
        bin.install "parq"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/a-poor/parq/releases/download/v0.1.0/parq_0.1.0_Darwin_x86_64.tar.gz"
      sha256 "2ee1431ad536eb1c47415cb33ce21eb04c98384968cefaf34da8f7893a7b18e6"

      def install
        bin.install "parq"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/a-poor/parq/releases/download/v0.1.0/parq_0.1.0_Linux_x86_64.tar.gz"
      sha256 "7f4e74d320179ce57e3fb71cc624d62ee7cc7620002d0095edd837d0468f7331"

      def install
        bin.install "parq"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/a-poor/parq/releases/download/v0.1.0/parq_0.1.0_Linux_arm64.tar.gz"
      sha256 "f93a3b4ea6da27366932c88c2081d226eb43453eb98b69019373de1ed9cfd4cc"

      def install
        bin.install "parq"
      end
    end
  end
end
