# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Parq < Formula
  desc "A CLI for examining parquet files."
  homepage "https://github.com/a-poor/parq"
  version "0.0.7"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/a-poor/parq/releases/download/v0.0.7/parq_0.0.7_Darwin_x86_64.tar.gz"
      sha256 "3bcfab5d69fc46a6842ee978057cd664a5c027d3d2fa8587fe7410b74d294abc"

      def install
        bin.install "parq"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/a-poor/parq/releases/download/v0.0.7/parq_0.0.7_Darwin_arm64.tar.gz"
      sha256 "c0df39e14c9c544cea9881785f00e9197519ccf793d7a8a33a47eb5a0ebad354"

      def install
        bin.install "parq"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/a-poor/parq/releases/download/v0.0.7/parq_0.0.7_Linux_arm64.tar.gz"
      sha256 "42ebd36fd45a3bb15bcf0e98cb593840b31128d87806eeffc2b4a5149424f362"

      def install
        bin.install "parq"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/a-poor/parq/releases/download/v0.0.7/parq_0.0.7_Linux_x86_64.tar.gz"
      sha256 "e09b2d8ccbd4b9030ff042e16ea9d7766a82b7c01f8289fb41e0685f189f064f"

      def install
        bin.install "parq"
      end
    end
  end
end
