# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Parq < Formula
  desc "A CLI for examining parquet files."
  homepage "https://github.com/a-poor/parq"
  version "0.0.8"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/a-poor/parq/releases/download/v0.0.8/parq_0.0.8_Darwin_arm64.tar.gz"
      sha256 "698dace7f9e0ff62f620c68eec9cc0a26bbad0697bb2f65636cccb0a8f0eccb7"

      def install
        bin.install "parq"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/a-poor/parq/releases/download/v0.0.8/parq_0.0.8_Darwin_x86_64.tar.gz"
      sha256 "12a3b141b6835ad283ffb029835fa37a1e31489bc0df7681954fe531f192c693"

      def install
        bin.install "parq"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/a-poor/parq/releases/download/v0.0.8/parq_0.0.8_Linux_x86_64.tar.gz"
      sha256 "57a5060ffc6d6a493f4a28d853d0d9b29939438109d903bc863ef650baceb5c7"

      def install
        bin.install "parq"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/a-poor/parq/releases/download/v0.0.8/parq_0.0.8_Linux_arm64.tar.gz"
      sha256 "f1dd09069f50c689fe075f9ae35c6c751f2d4ec93ac0a205a053ce09aee6ca5b"

      def install
        bin.install "parq"
      end
    end
  end
end
